[urgency=low]
background-color={{background | darken(0.55)}}f7
text-color={{foreground | lighten(0.5)}}
border-color={{color4}}

[urgency=normal]
background-color={{background | darken(0.55)}}f7
text-color={{foreground | lighten(0.5)}}
border-color={{color12}}

[urgency=critical]
background-color={{color1 | darken(0.35)}}f7
text-color={{foreground | lighten(0.5)}}
border-color={{color9}}
