# Wallust-generated ghostty colors
background = {{background | darken(0.55)}}
foreground = {{foreground | lighten(0.7)}}
cursor-color = {{foreground | lighten(0.7)}}
cursor-text = {{background | darken(0.55)}}
selection-background = {{color8 | darken(0.25)}}
selection-foreground = {{foreground | lighten(0.7)}}
palette = 0={{color0 | darken(0.4)}}
palette = 1={{color1 | saturate(0.6) | lighten(0.4)}}
palette = 2={{color2 | saturate(0.6) | lighten(0.4)}}
palette = 3={{color3 | saturate(0.6) | lighten(0.4)}}
palette = 4={{color4 | saturate(0.6) | lighten(0.4)}}
palette = 5={{color5 | saturate(0.6) | lighten(0.4)}}
palette = 6={{color6 | saturate(0.6) | lighten(0.4)}}
palette = 7={{color7 | lighten(0.3)}}
palette = 8={{color8}}
palette = 9={{color9 | saturate(0.8) | lighten(0.5)}}
palette = 10={{color10 | saturate(0.8) | lighten(0.5)}}
palette = 11={{color11 | saturate(0.8) | lighten(0.5)}}
palette = 12={{color12 | saturate(0.8) | lighten(0.5)}}
palette = 13={{color13 | saturate(0.8) | lighten(0.5)}}
palette = 14={{color14 | saturate(0.8) | lighten(0.5)}}
palette = 15={{color15 | lighten(0.3)}}
