# Wallust-generated kitty colors
foreground {{foreground | lighten(0.7)}}
background {{background | darken(0.55)}}
cursor {{foreground | lighten(0.7)}}
cursor_text_color {{background | darken(0.55)}}

active_tab_foreground {{background | darken(0.55)}}
active_tab_background {{color4}}
inactive_tab_foreground {{foreground | lighten(0.7)}}
inactive_tab_background {{color0 | darken(0.4)}}

active_border_color {{color4}}
inactive_border_color {{color8 | darken(0.25)}}

color0 {{color0 | darken(0.4)}}
color1 {{color1 | saturate(0.6) | lighten(0.4)}}
color2 {{color2 | saturate(0.6) | lighten(0.4)}}
color3 {{color3 | saturate(0.6) | lighten(0.4)}}
color4 {{color4 | saturate(0.6) | lighten(0.4)}}
color5 {{color5 | saturate(0.6) | lighten(0.4)}}
color6 {{color6 | saturate(0.6) | lighten(0.4)}}
color7 {{color7 | lighten(0.3)}}
color8 {{color8}}
color9 {{color9 | saturate(0.8) | lighten(0.5)}}
color10 {{color10 | saturate(0.8) | lighten(0.5)}}
color11 {{color11 | saturate(0.8) | lighten(0.5)}}
color12 {{color12 | saturate(0.8) | lighten(0.5)}}
color13 {{color13 | saturate(0.8) | lighten(0.5)}}
color14 {{color14 | saturate(0.8) | lighten(0.5)}}
color15 {{color15 | lighten(0.3)}}
