[urgency=low]
background-color={{background}}dd
text-color={{foreground | lighten(0.5)}}
border-color={{color4}}

[urgency=normal]
background-color={{background}}dd
text-color={{foreground | lighten(0.5)}}
border-color={{color12}}

[urgency=critical]
background-color={{color1}}dd
text-color={{foreground | lighten(0.5)}}
border-color={{color9}}
