#!/bin/sh
# Wallust-generated shell color variables
wallust_background="{{background}}"
wallust_foreground="{{foreground | lighten(0.5)}}"
wallust_color0="{{color0}}"
wallust_color1="{{color1}}"
wallust_color2="{{color2}}"
wallust_color3="{{color3}}"
wallust_color4="{{color4}}"
wallust_color5="{{color5}}"
wallust_color6="{{color6}}"
wallust_color7="{{color7}}"
wallust_color8="{{color8}}"
wallust_color9="{{color9}}"
wallust_color10="{{color10}}"
wallust_color11="{{color11}}"
wallust_color12="{{color12}}"
wallust_color13="{{color13}}"
wallust_color14="{{color14}}"
wallust_color15="{{color15}}"
