monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_63_00.6.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
