// IconPalette.qml
// Semantic, status-driven colors for the bar icons.
// Kept separate from Theme.json because that file is regenerated by wallust
// from the wallpaper — these stay stable so battery/wifi/etc. always read the same.
pragma Singleton
import QtQuick
import Quickshell
import qs.Settings

Singleton {
    id: root

    readonly property bool light: Settings.settings.lightMode

    // Neutral / off states
    readonly property color inactive: light ? "#8A8580" : "#7E756E"

    // Battery — green when healthy, warming through amber to red
    readonly property color batteryCharging: light ? "#0E9F6E" : "#5EE6A8"
    readonly property color batteryFull:     light ? "#2E8B45" : "#7BD88F"
    readonly property color batteryGood:     light ? "#5A9A22" : "#A8DE6E"
    readonly property color batteryMid:      light ? "#B07400" : "#FFD166"
    readonly property color batteryLow:      light ? "#C2570A" : "#FF9E64"
    readonly property color batteryCritical: light ? "#C62828" : "#FF6B6B"

    // WiFi — cyan when the link is good, amber when weak, red when down
    readonly property color wifiStrong: light ? "#0E8C97" : "#56D6E0"
    readonly property color wifiMedium: light ? "#1A96A0" : "#7FE0E8"
    readonly property color wifiWeak:   light ? "#B07400" : "#FFC46B"
    readonly property color wifiOff:    light ? "#C0392B" : "#F2777A"

    // Bluetooth — blue family
    readonly property color bluetoothConnected: light ? "#1565C0" : "#64B5F6"
    readonly property color bluetoothOn:        light ? "#3D5AFE" : "#7AA2FF"

    // Volume — violet
    readonly property color volume:      light ? "#7B3FBF" : "#C792EA"
    readonly property color volumeBoost: light ? "#C2570A" : "#FF9E64"
    readonly property color volumeMuted: inactive

    // Brightness — gold
    readonly property color brightness: light ? "#B07400" : "#FFD166"

    // System info
    readonly property color cpu:    light ? "#C2570A" : "#FF9E64"
    readonly property color memory: light ? "#6A3FBF" : "#BB9AF7"
    readonly property color tempCool: light ? "#2E8B45" : "#7BD88F"
    readonly property color tempWarm: light ? "#B07400" : "#FFD166"
    readonly property color tempHot:  light ? "#C62828" : "#FF6B6B"

    // Notifications
    readonly property color notify: light ? "#B07400" : "#FFD166"

    // Blend helper: nudge a color brighter on hover, in either mode
    function hover(base) {
        return light ? Qt.darker(base, 1.25) : Qt.lighter(base, 1.25);
    }

    // CPU temperature -> color ramp (celsius)
    function tempColor(celsius) {
        if (celsius >= 80)
            return tempHot;
        if (celsius >= 60)
            return tempWarm;
        return tempCool;
    }
}
